### ISSUE TITLE
Poppy\Faker\Provider\Base::__construct() must be an instance of Poppy\Faker\Generator

### ISSUE THREAD

**Issue by supgeek-rod** [imvkmark/poppy-faker#4]
在 `3.2.0` 和 `3.1.0` 版本使用报错如下:

```
Argument 1 passed to Poppy\Faker\Provider\Base::__construct() must be an instance of Poppy\Faker\Generator, instance of Faker\Generator given, called in /LARAVEL-APP/vendor/poppy/faker/src/Factory.php on line 28
```

https://github.com/imvkmark/poppy-faker/blob/8dd6b8983658e8106da8155cfca96b26727fb4e4/src/Factory.php#L17-L32

应该是 25 行，new 的对象错了？

**Comment by imvkmark** [comment]
是不是使用的时候还引入其他 faker 了 ? 为了兼容之前的 [fzaninotto/Faker](https://github.com/fzaninotto/Faker), 我保留了其项目的命名空间

如果有, 请描述使用场景, 因为 

```
namespace Faker;

class Generator extends \Poppy\Faker\Generator
{

}
```

所以也不会存在问题

**Comment by supgeek-rod** [comment]
OMG，我是 Laravel 项目，引入了 [fakerphp/faker](https://github.com/fakerphp/faker) 产生的问题。

[fzaninotto/Faker](https://github.com/fzaninotto/Faker) 包已经废弃。可以考虑使用 [fakerphp/faker](https://github.com/fakerphp/faker) 。

> This package is abandoned and no longer maintained. No replacement package was suggested.
>
> -- https://packagist.org/packages/fzaninotto/faker

受你项目启发，我自己写了个 [supgeek-rod/faker-zh](https://github.com/supgeek-rod/faker-zh)，特此感谢 ~

**Comment by imvkmark** [comment]
这个在我们项目中应用于 mock, 所以单独维护了一个包. 加油 奥利给
